[project]
name = "rag-chatbot"
version = "0.1.0"
description = "RAG based chatbot app"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
"langchain-community",
"langchain-chroma",
"langchain-openai",
"langchainhub",
"streamlit",
"atlassian-python-api",
]
